import type { ActivityDef } from './types';

export const ACTIVITIES: ActivityDef[] = [
  // ---- Hustles ----
  {
    id: 'beg',
    name: 'Ask for change',
    verb: 'Asked for change',
    desc: 'Sit with a sign and a cup. Better where there’s foot traffic.',
    category: 'hustle',
    kind: 'beg',
    days: 1,
    energy: 15,
    foodMult: 0.8,
    happiness: -0.4,
  },
  {
    id: 'scavenge',
    name: 'Collect cans & bottles',
    verb: 'Collected cans',
    desc: 'Walk the bins and return them for deposit. Street smarts find better routes.',
    category: 'hustle',
    kind: 'scavenge',
    days: 1,
    energy: 22,
    foodMult: 1.1,
  },
  {
    id: 'busk',
    name: 'Busk',
    verb: 'Busked',
    desc: 'Play for tips. Needs an instrument. Weather matters a lot.',
    category: 'hustle',
    kind: 'busk',
    days: 1,
    energy: 18,
    foodMult: 1,
    happiness: 0.3,
    requires: { any: [{ hasItem: ['harmonica'] }, { hasItem: ['guitar'] }] },
    requiresReason: 'You need an instrument. The pawn shop has a harmonica.',
    visible: { beat: ['first_money'] },
  },
  {
    id: 'oddjobs',
    name: 'Odd jobs',
    verb: 'Looked for odd jobs',
    desc: 'Moving help, yard work, cleanouts. Posted online; you need a working phone.',
    category: 'hustle',
    kind: 'oddJobs',
    days: 1,
    energy: 25,
    foodMult: 1.2,
    requires: { hasItem: ['phone', 'phone_plan'] },
    requiresReason: 'You need a phone with an active plan.',
    visible: { beat: ['first_money'] },
  },
  {
    id: 'daylabor',
    name: 'Day labor',
    verb: 'Went to the labor lot',
    desc: 'Show up at {laborLot} at 5am. If you’re picked, it’s a full day’s pay. If not, nothing.',
    category: 'hustle',
    kind: 'dayLabor',
    days: 1,
    energy: 40,
    foodMult: 1.4,
    requires: { hasItem: ['state_id', 'work_boots'] },
    requiresReason: 'Crews need a State ID and work boots.',
    visible: { beat: ['paperwork'] },
  },
  {
    id: 'deliveries',
    name: 'Deliveries',
    verb: 'Did deliveries',
    desc: 'Food and packages by bike through an app. Rain means surge pay.',
    category: 'hustle',
    kind: 'deliveries',
    days: 1,
    energy: 30,
    foodMult: 1.3,
    requires: { hasItem: ['bike', 'phone', 'phone_plan'] },
    requiresReason: 'You need a bike and a phone with an active plan.',
    visible: { beat: ['first_money'] },
  },

  // ---- Life ----
  {
    id: 'rest',
    name: 'Rest',
    verb: 'Rested',
    desc: 'Do nothing for a day. Your body needs it more than you think.',
    category: 'life',
    kind: 'rest',
    days: 1,
    energy: 0,
    foodMult: 0.7,
  },
  {
    id: 'clinic',
    name: 'Free clinic',
    verb: 'Went to the clinic',
    desc: 'Wait all day at the {clinic}. Usually you get seen.',
    category: 'life',
    kind: 'clinic',
    days: 1,
    energy: 5,
    foodMult: 0.8,
    visible: { minDay: 2 },
  },
  {
    id: 'library',
    name: 'Spend the day at the library',
    verb: 'Read at the library',
    desc: 'Warm, quiet, free. You learn things, and you feel like a person.',
    category: 'life',
    kind: 'library',
    days: 1,
    energy: 8,
    foodMult: 0.8,
    visible: { minDay: 4 },
  },
  {
    id: 'shelter_intake',
    name: 'Ask for a shelter bed',
    verb: 'Waited for a shelter bed',
    desc: 'Line up at the {shelter} and hope a cot opens.',
    category: 'life',
    kind: 'shelterIntake',
    days: 1,
    energy: 5,
    foodMult: 0.8,
    visible: { beat: ['meet_ines'], housing: ['street'] },
  },
  {
    id: 'dmv',
    name: 'Get a State ID',
    verb: 'Stood in line at the DMV',
    desc: 'Two days of lines at {dmv}. Bring your birth certificate and the fee.',
    category: 'life',
    kind: 'dmv',
    days: 2,
    energy: 10,
    foodMult: 0.8,
    requires: { hasItem: ['birth_certificate'] },
    requiresReason: 'Bring a birth certificate. Order one from {records}.',
    visible: { beat: ['paperwork'], lacksItem: ['state_id'] },
  },
];

export const activityById = (id: string) => ACTIVITIES.find((a) => a.id === id);
