// UI strings (English). One dictionary per locale; keys grouped by screen.
// Narrative content (events, story, codex) lives in the other content files.
export const STRINGS_EN = {
  // App / title
  'app.skip': 'Skip to game',
  'title.continue': 'Continue {name}',
  'title.newLife': 'Start a new life',
  'title.slot': 'Slot {n}',
  'title.empty': 'Empty',
  'title.slotMeta': 'Age {age} · Day {day} · {cash}',
  'title.slotDead': 'Life ended at {age}',
  'title.load': 'Load',
  'title.new': 'New',
  'title.delete': 'Delete',
  'title.deleteConfirm': 'Delete the life in slot {n}? This can’t be undone.',
  'title.import': 'Import a save file',
  'title.importTo': 'Import into slot {n}',
  'title.importFailed': 'Couldn’t import: {error}',
  'title.promise': 'No ads. No purchases. Works offline.',
  'title.debugged': 'debug',
  'title.version': 'v{version}',

  // Create
  'create.title': 'Who are you?',
  'create.name': 'Name',
  'create.namePlaceholder': 'Your name',
  'create.pronouns': 'Pronouns',
  'create.look': 'Look',
  'create.skin': 'Skin',
  'create.hair': 'Hair',
  'create.hairColor': 'Hair color',
  'create.facial': 'Facial hair',
  'create.top': 'Jacket',
  'create.accessory': 'Extra',
  'create.backstory': 'How did you get here?',
  'create.randomize': 'Randomize look',
  'create.seed': 'Seed (optional, for replaying a run)',
  'create.start': 'Begin',
  'create.back': 'Back',
  'create.nameRequired': 'Give your character a name.',

  // Top bar
  'top.cash': 'Cash',
  'top.bank': '+{bank} in bank',
  'top.life': 'Life left',
  'top.date': 'Date',
  'top.health': 'Health',
  'top.happy': 'Happy',
  'top.fed': 'Fed',
  'top.energy': 'Energy',
  'top.undo': 'Undo last action',
  'top.menu': 'Settings and saves',
  'top.age': 'Age {age}',

  // Tabs
  'tab.life': 'Life',
  'tab.hustle': 'Hustle',
  'tab.shop': 'Shop',
  'tab.money': 'Money',
  'tab.city': 'City',
  'tab.journal': 'Journal',
  'tab.new': 'New: {tab}',

  // Actions
  'act.do': 'Do it',
  'act.days': '{n} day',
  'act.daysPlural': '{n} days',
  'act.instant': 'No time',
  'act.x10': '×10',
  'act.x100': '×100',
  'act.until': 'Until…',
  'act.hold': 'Hold to repeat',
  'act.pays': '{min}–{max}',
  'act.paysFixed': '{pay}',
  'act.chance': '{p} chance',
  'act.expected': '≈{ev}/day expected',
  'act.energy': '−{n} energy',
  'act.why': 'What goes into this',
  'act.unavailable': 'Not available',

  // Life tab
  'life.goal': 'Next step',
  'life.needs': 'How you’re doing',
  'life.eat': 'Eat',
  'life.eatInstant': 'Eating takes no time',
  'life.care': 'Take care of yourself',
  'life.housing': 'Where you sleep',
  'life.currentHome': 'Current',
  'life.moveIn': 'Move in · {cost}',
  'life.giveUpBed': 'Give up this bed',
  'life.dog': 'Your dog',
  'life.dogFood': '{n} days of food left',
  'life.dogHungry': 'Hungry for {n} days',
  'life.dogBond': 'Bond',
  'life.dogBuy': 'Buy food in the Shop',
  'life.skills': 'Skills & standing',
  'life.showMore': 'Show details',
  'life.showLess': 'Hide details',
  'life.recent': 'Recently',
  'life.diet': 'Diet',
  'life.reputation': 'Reputation',
  'life.rentDue': 'Rent due in {n} days',
  'life.rentLate': 'Rent late: {owed} owed. Evicted in {n} days.',
  'life.shelterLeft': '{n} nights left at the shelter',
  'life.papers': 'Papers',
  'life.certArrives': 'Birth certificate arrives in {n} days',

  // Hustle tab
  'hustle.where': 'Working in {district}',
  'hustle.weather': 'Today: {weather}',
  'hustle.fatigue': 'This corner is {pct} worn out from asking',
  'hustle.goCity': 'Change district',
  'hustle.none': 'Nothing more to do here yet.',
  'hustle.autoEat': 'Batches auto-eat when you’re hungry',
  'hustle.autoEatOff': 'Auto-eat is off',

  // Shop tab
  'shop.owned': 'What you own',
  'shop.nothing': 'Just the clothes on your back.',
  'shop.buy': 'Buy',
  'shop.renew': 'Renew',
  'shop.expires': '{n} days left',
  'shop.ordered': 'On its way: arrives in {n} days',

  // Money tab
  'money.onHand': 'Cash on hand',
  'money.inBank': 'In the bank',
  'money.noBank': 'No bank account',
  'money.theft': 'Tonight’s theft risk: {p}',
  'money.theftNote': 'Only cash on hand can be stolen.',
  'money.open': 'Open an account ({min} deposit)',
  'money.deposit': 'Deposit',
  'money.withdraw': 'Withdraw',
  'money.all': 'All',
  'money.amount': 'Amount',
  'money.bills': 'Bills and renewals',
  'money.noBills': 'No bills. Nothing is owed to anyone. Small mercies.',
  'money.ledger': 'Every dollar in and out',
  'money.ledgerEmpty': 'No transactions yet.',
  'money.netWorth': 'Net worth {nw}',

  // City tab
  'city.travel': 'Go to {district}',
  'city.walk': 'Walk (1 day)',
  'city.bus': 'Bus (no time)',
  'city.here': 'You are here',
  'city.people': 'People you know',
  'city.locked': 'Locked',

  // Journal tab
  'journal.title': 'Journal',
  'journal.codex': 'Street Smarts',
  'journal.codexHint': 'Things you’ve figured out. Tap to read.',
  'journal.log': 'Everything that happened',
  'journal.empty': 'Nothing written yet.',

  // Modals
  'modal.continue': 'Continue',
  'modal.cancel': 'Cancel',
  'modal.close': 'Close',
  'modal.confirm': 'Confirm',
  'modal.learnMore': 'Read more in Street Smarts',
  'confirm.days': 'This takes {n} days of your life.',
  'confirm.cash': 'This costs {cost}, which is {pct} of what you have.',
  'confirm.batch': 'Repeat up to {n} times (up to {n} days). It stops early for events, story moments and warnings.',
  'confirm.dontAsk': 'Don’t ask again for batches',
  'confirm.giveUp': 'Give up your bed and go back to the street? You won’t get it back automatically.',
  'until.title': 'Repeat until…',
  'until.cash': 'I have at least',
  'until.health': 'Health drops below',
  'until.energy': 'Energy drops below',
  'until.food': 'Fed drops below',
  'until.max': 'At most this many days',
  'until.start': 'Start',
  'until.hint': 'Stops at whichever comes first, or for events, story moments and warnings.',
  'summary.title': 'While you were busy',
  'summary.days': 'Days passed',
  'summary.cash': 'Cash',
  'summary.bank': 'Bank',
  'summary.life': 'Life left',
  'summary.earned': 'Earned',
  'summary.food': 'Spent on food',
  'summary.stop.done': 'Finished.',
  'summary.stop.until': 'Stopped: your condition was met.',
  'summary.stop.event': 'Stopped: something happened.',
  'summary.stop.story': 'Stopped: a story moment.',
  'summary.stop.prompt': 'Stopped: something needs your attention.',
  'summary.stop.warning': 'Stopped: a warning.',
  'summary.stop.dead': 'Your life ended.',
  'summary.stop.unavailable': 'Stopped: {why}',
  'summary.highlights': 'What happened',
  'outcome.chance': 'You had a {p} chance.',
  'outcome.success': 'It worked.',
  'outcome.failure': 'It didn’t work out.',
  'event.odds': '{p} chance',
  'event.costs': 'Costs {cost}',
  'event.ev': 'EV {ev}',
  'warnings.title': 'Heads up',
  'dog.title': 'Name your dog',
  'dog.body': 'They’re going to need a name.',
  'dog.placeholder': 'A good name',
  'dog.ok': 'That’s the one',

  // Settings
  'settings.title': 'Settings',
  'settings.sound': 'Sound effects',
  'settings.motion': 'Motion',
  'settings.motionSystem': 'Follow system',
  'settings.motionOn': 'Full',
  'settings.motionReduce': 'Reduced',
  'settings.autoEat': 'Auto-eat during batches',
  'settings.confirmBatches': 'Confirm ×10 / ×100 batches',
  'settings.saves': 'Saves',
  'settings.export': 'Export save (JSON)',
  'settings.import': 'Import save',
  'settings.quit': 'Save and quit to title',
  'settings.newLife': 'Abandon this life',
  'settings.newLifeConfirm': 'End this life and return to the title screen? The save in this slot stays until you start a new life in it.',
  'settings.keys': 'Keyboard: 1–6 switch tabs · Z undo · ` debug · Esc closes',
  'settings.saved': 'Autosaved to slot {n} after every action.',
  'settings.seed': 'Run seed: {seed}',

  // Death
  'death.title': 'The end of {name}',
  'death.age': 'Died at {age} · Day {day}',
  'death.cause': 'Worn down most by {cause}.',
  'death.oldAge': 'Old age: a full life.',
  'death.journal': 'From the journal',
  'death.stats': 'The life in numbers',
  'death.newLife': 'Start another life',
  'death.export': 'Save this life to a file',
  'death.days': 'Days lived',
  'death.earned': 'Earned',
  'death.nw': 'Net worth',
  'death.home': 'Last home',

  // Stat tooltips
  'tip.cash.title': 'Cash',
  'tip.cash': 'Money on you right now: {cash}. Cash can be stolen at night (tonight’s risk: {risk}). {bank}',
  'tip.cash.bank': 'In the bank, safe: {bank}.',
  'tip.cash.nobank': 'A bank account (needs a State ID) keeps savings safe.',
  'tip.life.title': 'Life left',
  'tip.life': 'At your current pace you have {left} to live (age {age} now, expected to reach {expected}). Over the last {n} days you’ve been losing {rate} days of life per day. 1.0 is normal aging, higher means hard living is taking years off.',
  'tip.health.title': 'Health',
  'tip.health': 'Health {v}/100. Cold nights outside, hunger and exhaustion wear it down; shelter, good food and rest restore it. Below 40 it starts costing you life expectancy. At 0 you collapse.',
  'tip.happy.title': 'Happiness',
  'tip.happy': 'Happiness {v}/100. Below 20 you’re miserable: you earn 15% less and your life clock speeds up. A home, a dog, the library and rest all help.',
  'tip.fed.title': 'Fed',
  'tip.fed': 'Fed {v}/100. Drops about 28 a day, more on hard days. Below 20 you’re hungry (−20% income); at 0 you’re starving and health crashes. Eating takes no time.',
  'tip.energy.title': 'Energy',
  'tip.energy': 'Energy {v}/100. Work spends it; sleep brings back {sleep} a night where you sleep now. Below 20 you’re exhausted (−30% income, health suffers).',
  'tip.date.title': 'The calendar',
  'tip.date': '{date}. Season: {season}. Weather: {weather}. Weather changes street income, and nights outside hurt more in the cold.',
  'tip.diet': 'Diet quality {v}/100: a rolling average of what you eat. Above 70 adds to your life; below 30 takes from it.',
  'tip.rep': 'Reputation {v}. How the city sees you. Makes odd jobs easier to find.',

  'weather.clear': 'Clear',
  'weather.rain': 'Rain',
  'weather.snow': 'Snow',
  'weather.heat': 'Heatwave',
  'weather.cold': 'Bitter cold',
  'season.spring': 'Spring',
  'season.summer': 'Summer',
  'season.autumn': 'Autumn',
  'season.winter': 'Winter',
  'skill.streetSmarts': 'Street smarts',
  'skill.charisma': 'Charisma',
  'skill.trade': 'Trade',
  'skill.business': 'Business',
  'skill.music': 'Music',
  'cast.unknown': 'Not met yet',
} as const;
